name: Test All Utils

on:
  push:
    branches:
      - master

jobs:
  test_all_utils:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Test
        run: |
          go mod tidy
          go test ./...
        env:
          TZ: 'Asia/Hong_Kong'