name: Test Inside Docker
on:
  push:
    branches:
      - master

jobs:
  test_inside_docker:
    strategy:
      matrix:
        timezone: ['America/New_York', 'Asia/Hong_Kong', 'Europe/London']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test_inside_docker

